- hosts: localhost
  tasks: 
   - name: download and unzip maven
     unarchive: 
        copy=no 
        src=http://apache.mivzakim.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
        dest=.
        creates=./apache-maven-3.3.9
   - name: build docker image
     docker_image:
        path: .
        name: maven_copy
